add group image in home page
openml-labs/website pull request #16
Opened 2024-05-16 18:06 UTC by Taniya-Das

2024-05-17 14:36 UTC, PGijsbers requested changes
See note on the picture.

2024-05-17 14:36 UTC, PGijsbers commented on images/group_image.jpg
Please experiment a little with [squoosh](https://squoosh.app) to make the image file smaller. For example, make it WebP. Consider cropping it depending on the desired aspect ratio, and possibly increasing compression. Since this picture is on the landing page, we should be careful about making it load too much data.

2024-05-21 13:09 UTC, PGijsbers reviewed
Does this work for you? When I checked the rendered results on Github, and when I try it locally with `quarto render`, no image is added to the homepage.

2024-05-24 12:29 UTC, Taniya-Das commented
> Does this work for you? When I checked the rendered results on Github, and when I try it locally with `quarto render`, no image is added to the homepage.

Thanks, Corrected.

2024-05-28 09:15 UTC, PGijsbers approved these changes

2024-05-28 09:16 UTC, merged